"""R15.8/R15.9 optional training capability and governed adapter-training boundary.

Heavy ML packages are intentionally not imported here. They are capability-probed or
loaded only inside isolated workers launched by :class:`TrainingRuntime` or
:class:`TrainingRunner`.
"""

from .contracts import (
    CapabilityReport,
    CapabilityState,
    DTypeName,
    QuantizationMode,
    ResourceRequest,
    RuntimeDisposition,
    RuntimeRequest,
    SeedConfig,
    TrainingBackend,
    TuningRuntimeError,
)
from .distributed import (
    DistributedExecutionPlan,
    DistributedExecutionState,
    DistributedRankEvidence,
    DistributedRankSeed,
    DistributedRankState,
    DistributedTrainingReport,
    DistributedTrainingRunner,
    build_distributed_execution_plan,
)
from .distributed_recovery import (
    DistributedCheckpointManifest,
    DistributedRecoveryPlan,
    DistributedRecoveryRankEvidence,
    DistributedRecoveryReport,
    DistributedRecoveryRunner,
    build_distributed_checkpoint_manifest,
    build_distributed_recovery_plan,
)
from .kaggle_live_qualification import (
    KaggleLiveQualificationError,
    KaggleLiveQualificationRequest,
    build_private_probe_bundle,
    save_live_report,
    validate_live_evidence,
)
from .runtime import HostResourceProbe, TrainingRuntime, redact_runtime_text
from .strategy import (
    DeviceStrategyBudget,
    ExecutionStrategyPlan,
    RankSeed,
    StrategyBenchmarkDisposition,
    StrategyBenchmarkMeasurement,
    StrategyBenchmarkPolicy,
    StrategyBenchmarkReport,
    StrategyKind,
    build_execution_strategy_plan,
    evaluate_strategy_benchmark,
)
from .topology import (
    AcceleratorDevice,
    AcceleratorTopologyReport,
    ObservedAcceleratorTopology,
    ProviderAcceleratorRequest,
    SingleGpuSelection,
    TopologyDisposition,
    evaluate_single_gpu_selection,
)
from .training import (
    CheckpointRecord,
    DatasetBinding,
    LoraTrainingConfig,
    ModelBinding,
    SFTTrainingConfig,
    TrainingAuthorization,
    TrainingError,
    TrainingMode,
    TrainingPlan,
    TrainingReport,
    TrainingRunner,
    TrainingRunState,
)

__all__ = [
    "AcceleratorDevice",
    "AcceleratorTopologyReport",
    "CapabilityReport",
    "CapabilityState",
    "CheckpointRecord",
    "DTypeName",
    "DatasetBinding",
    "DistributedExecutionPlan",
    "DistributedExecutionState",
    "DistributedCheckpointManifest",
    "DistributedRankEvidence",
    "DistributedRankSeed",
    "DistributedRankState",
    "DistributedRecoveryPlan",
    "DistributedRecoveryRankEvidence",
    "DistributedRecoveryReport",
    "DistributedRecoveryRunner",
    "DistributedTrainingReport",
    "DistributedTrainingRunner",
    "DeviceStrategyBudget",
    "ExecutionStrategyPlan",
    "HostResourceProbe",
    "KaggleLiveQualificationError",
    "KaggleLiveQualificationRequest",
    "LoraTrainingConfig",
    "ModelBinding",
    "ObservedAcceleratorTopology",
    "ProviderAcceleratorRequest",
    "QuantizationMode",
    "RankSeed",
    "ResourceRequest",
    "RuntimeDisposition",
    "RuntimeRequest",
    "SFTTrainingConfig",
    "SeedConfig",
    "SingleGpuSelection",
    "StrategyBenchmarkDisposition",
    "StrategyBenchmarkMeasurement",
    "StrategyBenchmarkPolicy",
    "StrategyBenchmarkReport",
    "StrategyKind",
    "TopologyDisposition",
    "TrainingAuthorization",
    "TrainingBackend",
    "TrainingError",
    "TrainingMode",
    "TrainingPlan",
    "TrainingReport",
    "TrainingRunState",
    "TrainingRunner",
    "TrainingRuntime",
    "TuningRuntimeError",
    "build_distributed_checkpoint_manifest",
    "build_private_probe_bundle",
    "build_distributed_execution_plan",
    "build_distributed_recovery_plan",
    "build_execution_strategy_plan",
    "evaluate_single_gpu_selection",
    "evaluate_strategy_benchmark",
    "redact_runtime_text",
    "save_live_report",
    "validate_live_evidence",
]
