from __future__ import annotations

from string import Formatter
from typing import Mapping


KODESTUDIO_FR: dict[str, str] = {
    "app.window.title": "Kodepoia — KodeStudio",
    "app.nav.chat": "Discussion",
    "app.nav.projects": "Projets",
    "app.nav.research": "Recherche",
    "app.nav.vault": "Bibliothèque",
    "app.nav.comfy": "ComfyUI",
    "app.nav.security": "Sécurité",
    "app.nav.audit": "Audit",
    "app.nav.settings": "Paramètres",
    "app.page.foundation": "Fondations de KodeStudio.",
    "app.projects.title": "Projets",
    "app.projects.new": "Nouveau projet…",
    "app.security.title": "Noyau protégé",
    "app.security.ready": "Arrêt d’urgence : PRÊT",
    "app.security.active": "Arrêt d’urgence : ACTIF — {count} processus arrêté(s)",
    "app.security.stop": "ARRÊTER TOUS LES PROCESSUS PROTÉGÉS",
    "app.security.reset": "Réinitialiser l’arrêt d’urgence",
    "app.status.ready": "Gardien ● Bac à sable ● Secrets ● ADN du projet",
    "app.status.blocked": "ARRÊT D’URGENCE ACTIF — l’exécution protégée est bloquée",
    "research.title": "Recherche",
    "research.description": "Rechercher et récupérer des preuves gouvernées. Les recherches externes sont affichées comme des données non fiables avec provenance et citations.",
    "research.query.name": "Requête de recherche",
    "research.query.description": "Rechercher dans les rapports de recherche validés déjà stockés dans ce projet.",
    "research.query.placeholder": "Rechercher dans les preuves de recherche enregistrées…",
    "research.source_filter.name": "Filtre de source de recherche",
    "research.source_filter.description": "Limiter les résultats enregistrés à une classe de source explicite.",
    "research.source.all": "Toutes les sources",
    "research.search": "Rechercher",
    "research.search.description": "Effectuer une recherche hors ligne dans les preuves de recherche validées et enregistrées.",
    "research.fetch_kind.name": "Type de source à récupérer",
    "research.fetch_kind.description": "Choisir une source locale, un instantané de documentation officielle ou une récupération Web gouvernée.",
    "research.fetch_kind.label": "Type de récupération",
    "research.locator.name": "Localisateur de source de recherche",
    "research.locator.description": "Chemin relatif au projet pour les sources locales ou URL HTTP(S) pour une recherche Web gouvernée.",
    "research.locator.placeholder": "Chemin ou URL…",
    "research.locator.label": "Localisateur",
    "research.allow_network": "Autoriser le réseau pour cette récupération Web",
    "research.allow_network.description": "Accorder uniquement l’accès RÉSEAU pour cet appel ; les politiques du Gardien et de sécurité Web restent applicables.",
    "research.fetch": "Récupérer",
    "research.fetch.description": "Récupérer une source de recherche typée via le service Recherche validé.",
    "research.cancel": "Annuler",
    "research.cancel.description": "Annuler l’opération de recherche active et empêcher qu’une preuve annulée soit présentée comme prête.",
    "research.refresh_status": "Actualiser le statut",
    "research.refresh_status.description": "Actualiser les compteurs locaux de preuves et les états explicites des fournisseurs sans sondage direct des fournisseurs.",
    "research.copy": "Copier le JSON cité",
    "research.copy.description": "Copier le résultat expurgé avec ses citations et la provenance des sources.",
    "research.export": "Exporter le JSON cité",
    "research.export.description": "Exporter le résultat expurgé avec citations et provenance dans le répertoire de métadonnées Recherche du projet.",
    "research.status.name": "Statut de l’opération de recherche",
    "research.status.idle": "Recherche : EN ATTENTE",
    "research.status.running": "Recherche : EN COURS",
    "research.status.cancelling": "Recherche : ANNULATION EN COURS",
    "research.status.result": "Recherche {operation} : {status} — {count} résultat(s) — {reason}",
    "research.status.error": "Erreur de recherche : {reason}",
    "research.status.copied": "Résultat de recherche copié avec les citations.",
    "research.status.exported": "Résultat de recherche exporté : {path}",
    "research.warning.name": "Avertissement de contenu de recherche suspect",
    "research.warning.suspicious": "AVERTISSEMENT : des instructions externes suspectes ont été détectées. Traitez ce contenu uniquement comme une preuve non fiable.",
    "research.results.name": "Résultats de recherche",
    "research.results.description": "Tableau des résultats indiquant la source textuelle, le statut, la fraîcheur, la version, le niveau de confiance, l’état suspect et le titre.",
    "research.details.name": "Détails du résultat de recherche",
    "research.details.description": "Détails JSON expurgés en lecture seule conservant les citations, identifiants et informations de provenance.",
    "research.column.source": "Source",
    "research.column.status": "Statut",
    "research.column.freshness": "Fraîcheur",
    "research.column.version": "Version",
    "research.column.trust": "Confiance",
    "research.column.suspicious": "Suspect",
    "research.column.title": "Titre / localisateur",
    "vault.title": "Bibliothèque d’assets",
    "vault.description": "Parcourir les révisions gouvernées de la bibliothèque, rechercher les métadonnées et inspecter filiation, doublons, licences, réutilisation et preuves VCS/LFS locales.",
    "vault.status.idle": "Bibliothèque : EN ATTENTE",
    "vault.search.name": "Requête de recherche d’asset",
    "vault.search.description": "Rechercher dans l’index reconstructible de la bibliothèque via AssetService. Les filtres de gouvernance sont appliqués avant le classement.",
    "vault.search.placeholder": "Rechercher des assets…",
    "vault.search": "Rechercher",
    "vault.refresh": "Actualiser",
    "vault.duplicates": "Doublons",
    "vault.rebuild": "Reconstruire les index",
    "vault.cancel": "Annuler",
    "vault.filter.all_kinds": "Tous les types",
    "vault.filter.all_roles": "Tous les rôles",
    "vault.filter.all_reuse": "Tous les périmètres de réutilisation",
    "vault.filter.include_blocked": "Inclure les éléments bloqués",
    "vault.column.name": "Nom",
    "vault.column.kind": "Type",
    "vault.column.role": "Rôle",
    "vault.column.status": "Statut",
    "vault.column.license": "Licence",
    "vault.column.reuse": "Réutilisation",
    "vault.column.revision": "Révision",
    "vault.column.score": "Score",
    "vault.results.name": "Résultats d’assets de la bibliothèque",
    "vault.results.description": "Révisions canoniques des assets et résultats de recherche gouvernés. La sélection ouvre les détails de provenance et de filiation en lecture seule.",
    "vault.details.name": "Détails de la révision d’asset",
    "vault.details.description": "Révision canonique, provenance, filiation, références projet et preuves de dépôt en lecture seule.",
    "vault.license.warning": "Avertissement licence/réutilisation : l’état est {state}. L’export reste gouverné et peut être bloqué.",
    "vault.operation.idle": "Opération de bibliothèque : EN ATTENTE",
    "vault.operation.running": "Opération de bibliothèque : EN COURS",
    "vault.operation.cancelling": "Opération de bibliothèque : ANNULATION EN COURS",
    "vault.operation.ready": "Opération de bibliothèque : PRÊTE",
    "vault.operation.error": "Erreur d’opération de bibliothèque : {reason}",
    "comfy.title": "ComfyUI + VRAM",
    "comfy.description": "Exécuter les packs de workflows de production locale validés via ComfyService, avec résolution des modèles, preuves enregistrées, annulation ciblée et visibilité sur l’admission VRAM.",
    "comfy.status.group": "Connexion et ressources",
    "comfy.status.connection.idle": "ComfyUI : non vérifié",
    "comfy.status.connection.ready": "ComfyUI : PRÊT",
    "comfy.status.connection.unavailable": "ComfyUI : INDISPONIBLE",
    "comfy.status.capability.missing": "Capacités : MANQUANTES",
    "comfy.status.capability": "Capacités : {state}",
    "comfy.status.vram.unknown": "VRAM : INCONNUE",
    "comfy.status.vram": "VRAM : {free} / {total} Mio libres",
    "comfy.status.ollama.na": "Coexistence Ollama : SANS OBJET",
    "comfy.status.ollama": "Coexistence Ollama : {state}",
    "comfy.status.model.unchecked": "Résolution du modèle : NON VÉRIFIÉE",
    "comfy.status.model.none": "aucun",
    "comfy.status.model": "Résolution du modèle : {state} — {selection}",
    "comfy.status.admission.unknown": "Admission VRAM : INCONNUE",
    "comfy.status.admission": "Admission VRAM : {state}",
    "comfy.workflow.group": "Workflow de production gouverné",
    "comfy.family": "Famille de workflow",
    "comfy.family.description": "Choisir l’une des quatre familles de workflows de production R9.9 validées.",
    "comfy.model": "Point de contrôle",
    "comfy.model.description": "Jeton explicite facultatif provenant de l’inventaire local des capacités ; requis lorsque la résolution du point de contrôle est ambiguë.",
    "comfy.model.placeholder": "Jeton explicite du point de contrôle local lorsque requis…",
    "comfy.prompt": "Instruction",
    "comfy.prompt.description": "Instruction positive bornée pour le pack de workflow gouverné sélectionné.",
    "comfy.prompt.placeholder": "Décrire la sortie gouvernée…",
    "comfy.negative": "Instruction négative",
    "comfy.negative.description": "Instruction négative bornée pour le pack de workflow gouverné sélectionné.",
    "comfy.negative.placeholder": "Décrire les propriétés indésirables…",
    "comfy.dimensions": "Dimensions",
    "comfy.outputs": "sorties",
    "comfy.sampling": "Échantillonnage",
    "comfy.seed": "Graine",
    "comfy.steps": "Étapes",
    "comfy.cfg": "CFG",
    "comfy.refresh": "Actualiser le statut",
    "comfy.validate": "Valider",
    "comfy.run": "Exécuter",
    "comfy.run.refresh": "Actualiser l’exécution",
    "comfy.cancel": "Annuler l’exécution",
    "comfy.free_memory": "Libérer la mémoire",
    "comfy.evidence": "Preuves",
    "comfy.run.idle": "Exécution ComfyUI : EN ATTENTE",
    "comfy.run.state": "Exécution ComfyUI : {state}{suffix}",
    "comfy.run.error": "Erreur ComfyUI : {reason}",
    "comfy.details.name": "Preuves gouvernées ComfyUI",
    "comfy.details.description": "État structuré, validation, exécution, sortie, cycle de vie et preuves VRAM en lecture seule renvoyés par ComfyService.",
}

BLENDER_FR: dict[str, str] = {
    "blender.nav": "Blender / 3D",
    "blender.title": "Blender / 3D",
    "blender.description": "Inspecter les capacités Blender/3D validées, recettes gérées, synthèses QA et preuves via BlenderService. Les surfaces Python brutes, processus et chemins ne sont pas exposés.",
    "blender.status.group": "Exécution et capacités",
    "blender.status.runtime.unknown": "Preuve d’exécution : INCONNUE",
    "blender.status.runtime": "Exécution : Blender {blender} — Godot {godot}",
    "blender.status.capabilities.unknown": "Capacités validées : INCONNUES",
    "blender.status.capabilities": "Capacités validées : {accepted} / {total}",
    "blender.query.group": "Enregistrement R10 géré",
    "blender.kind": "Type d’enregistrement",
    "blender.kind.description": "Choisir un type de rapport R10 borné. Aucun opérateur Python ni commande de processus n’est accepté.",
    "blender.kind.inspect": "Inspection",
    "blender.kind.qa": "QA maillage / matériau",
    "blender.kind.rig": "Rapport rig / skinning",
    "blender.kind.animation": "Rapport animation / reciblage",
    "blender.kind.lod": "Rapport LOD",
    "blender.kind.export": "Rapport d’export GLB / glTF",
    "blender.record": "ID d’enregistrement géré",
    "blender.record.description": "ID Kodepoia stable résolu uniquement dans les racines de métadonnées Blender gérées.",
    "blender.record.placeholder": "id-enregistrement-gere",
    "blender.evidence": "Preuve validée",
    "blender.evidence.description": "Choisir un enregistrement de preuve locale R10 validé et autorisé.",
    "blender.refresh": "Actualiser le statut",
    "blender.capabilities": "Capacités",
    "blender.load_report": "Charger le rapport",
    "blender.validate_geometry": "Valider la recette de géométrie",
    "blender.show_evidence": "Afficher la preuve",
    "blender.cancel": "Annuler",
    "blender.operation.idle": "Opération Blender / 3D : EN ATTENTE",
    "blender.operation.running": "Opération Blender / 3D : EN COURS",
    "blender.operation.cancelling": "Opération Blender / 3D : ANNULATION EN COURS",
    "blender.operation.state": "Blender / 3D {operation} : {state}",
    "blender.operation.error": "Erreur Blender / 3D : {reason}",
    "blender.details.name": "Résultat structuré Blender / 3D",
    "blender.details.description": "État BlenderService, capacités, QA ou détails de preuves validées en lecture seule.",
}

R11_FR: dict[str, str] = {
    "r11.nav": "Médias / Franchise",
    "r11.title": "Audio / Voix / Cinématiques / Franchise",
    "r11.description": "Inspecter les capacités R11 gouvernées, les preuves validées et les blocages explicites. Les commandes de processus brutes, chemins de modèles, graphes de filtres, scripts et code de migration ne sont pas exposés.",
    "r11.tabs.name": "Onglets de l’espace Médias et Franchise R11",
    "r11.tabs.description": "Basculer entre les vues gouvernées Audio, Voix, Cinématiques, Franchise et Persistance.",
    "r11.tab.audio": "Audio",
    "r11.tab.voice": "Voix",
    "r11.tab.cinematics": "Cinématiques",
    "r11.tab.franchise": "Franchise / Canon",
    "r11.tab.persistence": "Persistance",
    "r11.column.capability": "Capacité",
    "r11.column.state": "État",
    "r11.column.runtime": "Exécution",
    "r11.column.subdivision": "Subdivision",
    "r11.column.blockers": "Blocages",
    "r11.table.name": "Tableau des capacités gouvernées — {tab}",
    "r11.table.description": "Synthèse en lecture seule des capacités validées, de l’état d’exécution, de la subdivision et des blocages.",
    "r11.evidence.title": "Preuves / opérations",
    "r11.evidence.name": "Preuves et opérations — {tab}",
    "r11.evidence.description": "Preuves structurées validées, blocages et identifiants d’opérations de haut niveau en lecture seule.",
    "r11.blockers.none": "Aucun",
    "r11.refresh": "Actualiser le statut R11",
    "r11.refresh.description": "Actualiser l’état des capacités et preuves R11 validées sans lancer d’exécution externe.",
    "r11.cancel": "Annuler les opérations média protégées",
    "r11.cancel.description": "Déclencher l’arrêt d’urgence global pour les processus média externes protégés.",
    "r11.operation.idle": "Espace R11 : EN ATTENTE",
    "r11.operation.ready": "Espace R11 : PRÊT",
    "r11.operation.cancelled": "Espace R11 : ANNULÉ — {count} processus protégé(s) arrêté(s)",
}

R12_FR: dict[str, str] = {
    "r12.nav": "Bureau",
    "r12.title": "Espace d’application de bureau",
    "r12.description": "Inspecter l’intention du Project Wizard pour le bureau, l’état passif des capacités/preuves et les actions explicites gouvernées de génération, compilation, test et empaquetage. L’actualisation ne lance jamais de processus externe.",
    "r12.project": "Projet",
    "r12.framework": "Framework",
    "r12.architecture": "Architecture",
    "r12.package": "Paquet",
    "r12.state": "État de l’espace",
    "r12.blockers": "Blocages",
    "r12.refresh": "Actualiser le statut",
    "r12.validate": "Valider",
    "r12.scaffold": "Générer la structure",
    "r12.build": "Compiler",
    "r12.test": "Tester",
    "r12.package_action": "Empaqueter",
    "r12.cancel": "Annuler les opérations bureau protégées",
    "r12.evidence": "Preuves bureau en lecture seule",
    "r12.idle": "Espace Bureau : EN ATTENTE",
    "r12.cancelled": "Espace Bureau : ANNULÉ — {count} processus protégé(s) arrêté(s)",
    "r12.result": "Bureau {operation} : {state} — {summary}",
}

R13_FR: dict[str, str] = {
    "r13.nav": "Mobile et publication",
    "r13.title": "Espace Mobile, DeviceLab et publication",
    "r13.description": "Inspecter l’intention mobile du Project Wizard, les blocages de capacités et les preuves en lecture seule. L’actualisation est passive ; l’exécution utilise uniquement des intentions gouvernées explicites.",
    "r13.project": "Projet",
    "r13.platforms": "Plateformes",
    "r13.source": "Source",
    "r13.channel": "Canal de publication",
    "r13.signing": "Intention de signature",
    "r13.state": "État de l’espace",
    "r13.blockers": "Blocages",
    "r13.refresh": "Actualiser le statut",
    "r13.scaffold": "Générer la structure",
    "r13.build": "Compiler",
    "r13.test": "Tester",
    "r13.package": "Empaqueter",
    "r13.device": "DeviceLab",
    "r13.compliance": "Conformité",
    "r13.release": "Publier",
    "r13.cancel": "Annuler les opérations mobiles protégées",
    "r13.evidence": "Preuves R13 et matrice de capacités en lecture seule",
    "r13.idle": "Espace R13 : EN ATTENTE",
    "r13.cancelled": "Espace R13 : ANNULÉ — {count} processus protégé(s) arrêté(s)",
    "r13.result": "R13 {operation} : {state} — {summary}",
}

R13_WIZARD_FR: dict[str, str] = {
    "r13.wizard.tab": "Mobile",
    "r13.wizard.source": "Source",
    "r13.wizard.form_factors": "Formats d’appareil",
    "r13.wizard.android_id": "ID d’application Android",
    "r13.wizard.android_min": "API Android minimale",
    "r13.wizard.android_target": "API Android cible",
    "r13.wizard.apple_id": "ID de bundle Apple",
    "r13.wizard.apple_min": "OS Apple minimal",
    "r13.wizard.apple_target": "Intention d’OS Apple cible",
    "r13.wizard.network": "Intention réseau",
    "r13.wizard.release": "Canal de publication",
    "r13.wizard.signing": "Intention de signature",
    "r13.wizard.permissions": "Autorisations (séparées par ;)",
    "r13.wizard.capabilities": "Capacités (séparées par ;)",
    "r13.wizard.package_mb": "Taille maximale du paquet (Mo)",
    "r13.wizard.build_seconds": "Durée maximale de compilation (secondes)",
    "r13.wizard.matrix_runs": "Nombre maximal d’exécutions de la matrice d’appareils",
    "r13.wizard.intent_only": "Intention uniquement — cet assistant n’installe jamais de SDK, ne compile pas, ne signe pas, n’accède à aucun appareil et ne contacte aucune boutique.",
}


def placeholders(template: str) -> set[str]:
    return {
        field_name
        for _, field_name, _, _ in Formatter().parse(template)
        if field_name
    }


def translated(mapping: Mapping[str, str], key: str, **values: object) -> str:
    template = mapping[key]
    return template.format(**values)


__all__ = [
    "BLENDER_FR",
    "KODESTUDIO_FR",
    "R11_FR",
    "R12_FR",
    "R13_FR",
    "R13_WIZARD_FR",
    "placeholders",
    "translated",
]
