"""Governed desktop-application contracts and boundaries for R12."""

from .boundary import DesktopBoundaryError, DesktopToolchainBoundary, validate_environment_overrides
from .contracts import (
    DesktopArchitecture,
    DesktopCapabilityReport,
    DesktopCapabilityState,
    DesktopFramework,
    DesktopOS,
    DesktopPackageKind,
    DesktopTargetProfile,
    DesktopToolKind,
    DesktopToolchainIdentity,
    canonical_sha256,
)
from .scaffold import (
    DesktopScaffoldEngine,
    DesktopTemplateManifest,
    FileOwnership,
    PreviewAction,
    RenderedFile,
    ScaffoldLineage,
    ScaffoldPreview,
    TemplateFile,
    TemplateValue,
    TemplateValueKind,
    WorkspaceManifest,
)

__all__ = [
    "DesktopArchitecture",
    "DesktopBoundaryError",
    "DesktopCapabilityReport",
    "DesktopCapabilityState",
    "DesktopFramework",
    "DesktopOS",
    "DesktopPackageKind",
    "DesktopScaffoldEngine",
    "DesktopTargetProfile",
    "DesktopTemplateManifest",
    "DesktopToolKind",
    "DesktopToolchainBoundary",
    "DesktopToolchainIdentity",
    "FileOwnership",
    "PreviewAction",
    "RenderedFile",
    "ScaffoldLineage",
    "ScaffoldPreview",
    "TemplateFile",
    "TemplateValue",
    "TemplateValueKind",
    "WorkspaceManifest",
    "canonical_sha256",
    "validate_environment_overrides",
]
